version: 2.0
jobs:
  build:
    docker:
      - image: xarthisius/girder:test
      - image: mongo:3.2
    steps:
      - checkout
      - run:
          name: Installing Plugin Dependencies
          command: |
            ln -s /root/project /girder/plugins/ythub
            set -o pipefail; pip install -r requirements.txt | cat
      - run:
          name: Running Tests
          environment:
            - FOO: "bar"
            - PYTHON_VERSION: "3.4"
            - COVERAGE_EXECUTABLE: "/usr/local/bin/coverage"
            - FLAKE8_EXECUTABLE: "/usr/local/bin/flake8"
            - VIRTUALENV_EXECUTABLE: "/usr/local/bin/virtualenv"
            - PYTHON_EXECUTABLE: "/usr/bin/python3"
            - TEST_GROUP: "python"
          command: |
            mkdir /girder/build
            ctest -VV -S /girder/plugins/ythub/cmake/circle_continuous.cmake -T Test --no-compress-output
            mkdir /reports
            ls -l /build/Testing
            xsltproc /girder/cmake/ctest2junix.xsl /build/Testing/$(head -n 1 /build/Testing/TAG)/Test.xml > /reports/CTestResults.xml
      - run:
          name: Uploading Coverage Results
          working_directory: /girder/build
          command: |
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /reports
